### ISSUE TITLE
Telerik's new anti-tampering protection

### ISSUE THREAD

**Issue by tcortega** [pjy612/fiddler-everywhere-enhance#4]
Is it just me but seems like since 4.2.1 they added new security making it pretty much impossible to modify dlls without breaking the whole thing? Did you have any luck

**Comment by pjy612** [comment]
Code protection has been used since 4.1.0, but the windows environment only applies to WebUi. it was only in 4.2 and later versions that other related Dlls were fully applied.

**Comment by tcortega** [comment]
> Code protection was used from 4.1.0 onwards, but the windows environment only applied to WebUi, and only in 4.2 was it fully applied to other related Dlls.

Did anyone manage to find a way to modify it without breaking everything? I tried directly altering the IL code but it still, for some reason, breaks everything. I can't even install old versions in order to use them either.

**Comment by pjy612** [comment]
recommend using version 4.0.1, which is the last unprotected version. Basically, you can modify the front and back-end code freely.

**Comment by tcortega** [comment]
> recommend using version 4.0.1, which is the last unprotected version. Basically, you can modify the front and back-end code freely.

Do you have it's files? I tried installing it, by downloading an outdated version of the installer. But it still manages to automatically update itself somehow.

**Comment by pjy612** [comment]
in ReadMe.md 
Modify `%userprofile%\.fiddler\Settings\electron-settings.json` and search for `autoUpdateSettings` to add
```
"autoUpdateSettings": {
    "downloadedUpdateVersion": "0.0.0",
    "disabled":true
}
```
disabled autoUpdate.

old version
https://downloads.getfiddler.com/win/Fiddler%20Everywhere%204.0.1.exe

**Comment by pjy612** [comment]
If you want to modify the new version of the dll, you need to remove the code protection (.Net Reactor).
But there is no fully applicable cracking tool.

The latest relevant tool is 
https://github.com/SychicBoy/NETReactorSlayer
However, it does not yet support

**Comment by Dastano** [comment]
You plan on releasing a 4.3.2 Version? I saw the push you made, but I guess its not defeated the Check yet.

**Comment by pjy612** [comment]
> You plan on releasing a 4.3.2 Version? I saw the push you made, but I guess its not defeated the Check yet.

It is recommended to use v4.0.1, as versions after v4.2.x do not guarantee that all features will work correctly.

**Comment by Dastano** [comment]
> > You plan on releasing a 4.3.2 Version? I saw the push you made, but I guess its not defeated the Check yet.
> 
> It is recommended to use v4.0.1, as versions after v4.2.x do not guarantee that all features will work correctly.

Will we get any issue with: Migrate Your Subscription!  Fiddler is migrating to the unified Telerik system for subscription management.  [See the migration steps.](https://github.com/pjy612/fiddler-everywhere-enhance/issues/4#) 

at some point?

Do you know if any Feature is missing on 4.2.X? I tried to run 4.3.2 with crack, but it keeps blank, so prob. it detects tampering.

**Comment by pjy612** [comment]
> > > You plan on releasing a 4.3.2 Version? I saw the push you made, but I guess its not defeated the Check yet.
> > 
> > 
> > It is recommended to use v4.0.1, as versions after v4.2.x do not guarantee that all features will work correctly.
> 
> Will we get any issue with: Migrate Your Subscription! Fiddler is migrating to the unified Telerik system for subscription management. [See the migration steps.](https://github.com/pjy612/fiddler-everywhere-enhance/issues/4#)
> 
> at some point?
> 
> Do you know if any Feature is missing on 4.2.X? I tried to run 4.3.2 with crack, but it keeps blank, so prob. it detects tampering.

I don't know, that's why v4.0.1 is recommended, at least this version is transparent
